### ISSUE TITLE
mjpg-streamer not staying alive

### ISSUE THREAD

**Issue by wiwa5607** [fredrikbaberg/hassio-addons#195]
I am using the mjpg-streamer addon from this repo to stream my webcam to an open port and then onto the Octoprint addon. The stream works well when the mjpg-streamer is started, but after about 30 mins the stream no longer works. Once the stream is gone, the mjpg-streamer log has this message "NOTICE    Oct 13 13:47:28 [258]: Waiting servers (0) is less than MinSpareServers (2). Creating new child." repeatedly until I restart the addon manually. Once I manually restart, the stream is back for ~30 mins again. 

Here are my input arguments: input_uvc.so -d _camera_device_id_ -r 1920x1080 -f 30

**Comment by fredrikbaberg** [comment]
I'm not currently using the separate addon, but I'll see if I can figure out why that happens.
What hardware are you using? Anything else in the log?

I believe that notice is from the proxy server (tinyproxy), are you accessing the stream from multiple devices at the same time?

I'll do some changes and publish a new version, should be up within a few hours.

**Comment by fredrikbaberg** [comment]
Could you see if version 0.3.0 solves the issue? It should be available now. I've updated the version of Tinyproxy (saw what seemed to be a related issue which should be fixed with version 1.11.0) and adjusted the proxy config to match.

I'll see if I can fix the "upstream proxy" thing later, I don't think that is related but it does not look nice. 

I don't have Home Assistant running on my Raspberry Pi at the moment, so can't test it with camera right now.

**Comment by wiwa5607** [comment]
The version did get rid of the "Creating new child" errors, but the "upstream proxy" is still showing up. 

I can try with the mjpg-streamer that's builtin to the octoprint addon, it was giving me issues earlier, but I do need to try refreshing the install.
